### ISSUE TITLE
Карта ответов 

### ISSUE THREAD

**Issue by ghost** [AlsaAsksMiley/2ch-ua-flagger#1]
Большое спасибо за скрипт, заметил, что флажки не отображаются со включенным куклоскриптом, когда на нулевой смотришь в карту ответов. https://i.imgur.com/hTMWl2N.png

**Comment by AlsaAsksMiley** [comment]
Действительно, было такое. Произошло из-за того, что MutationObserver был настроен на отслеживание изменений в ноде с классом "thread". Естественно, на нулевой много таких нод, но это не самое главное — при навигации по рефлинкам куклоскрипт подгружает новые элементы на тот же уровень в DOM, на котором находится тред, из-за этого MutationObserver не видел изменений в структуре документа. Частично эту проблему удалось решить, указав в качестве узла слежения форму, в которой содержатся все посты и треды. Однако с выключенной куклой всё ещё не происходит замена текста на иконки у первого подгружаемого по рефлинку поста. Связано это с тем, что при наведении мыши на рефлинк происходит вставка поста-пустышки, содержащего надпись "Загрузка...". Замена происходит при отладке сценария пошагово, но наверно потому что макаба успевает подгрузить внутреннюю структуру поста или же потому что обсервер замечает изменение подгружаемого поста.
tl;dr
Остался другой неприятный баг в случае, если кукла выключена.

**Comment by AlsaAsksMiley** [comment]
Судя по всему, исправление не пошло на пользу: теперь сломалась замена иконок для автоматически подгружаемых в треде постов.

**Comment by ghost** [comment]
Можешь по этому поводу посмотреть здесь: http://pastebin.com/raw.php?i=NzDkWsY5 
В этом скрипте работает.

**Comment by AlsaAsksMiley** [comment]
Я исправил проблему с подгрузкой, надо было Mutation Observer сообщить, чтобы он отслеживал изменения не только у дочерних элементов, но также и у их потомков.
Но всё равно осталась проблема с подгрузкой первого поста по рефлинку на другой тред в случае, когда кукла не работает. Займусь им позже.

**Comment by ghost** [comment]
Еще у тебя флажки вверх уехали, можешь добавить к case0 и case1:

```
        img_node.setAttribute("style", "vertical-align: -2px");
```

**Comment by AlsaAsksMiley** [comment]
Ошибка исправлена.

**Comment by AlsaAsksMiley** [comment]
Насчет смещения иконок — для этой проблемы заведу новое обсуждение, потому что это обсуждение относится к другой проблеме, которая была исправлена, поэтому закрывается.

**Comment by AlsaAsksMiley** [comment]
Собственно, открывать новые обсуждения не нужно, смещение исправлено
