### ISSUE TITLE
Бесконечная прокрутка + куклоскрипт 

### ISSUE THREAD

**Issue by ghost** [AlsaAsksMiley/2ch-ua-flagger#2]
В куклоскрипт запилили бесконечную прокрутку и теперь с ней иконки не грузятся на следующих страницах.

**Comment by AlsaAsksMiley** [comment]
Хмм, посмотрю.

**Comment by AlsaAsksMiley** [comment]
Коммит 9ceac73 исправляет эту проблему.

Дело было в том, что при включенной бесконечной прокрутке новые треды подгружались не в существующую форму, а в новую, которая размещалась в `<section class="posts"></section>`. DOMObserver не видел этих изменений, потому что наблюдал за самой первой формой в `<section>`.
